/**
 * Generate supabase/seed.sql — the fixture data as plain SQL, for pasting
 * into the Supabase SQL editor when running scripts/seed.ts isn't convenient
 * (e.g. no service-role key on hand, or restricted network).
 *
 *   npx tsx scripts/generate-seed-sql.ts
 *
 * Mirrors scripts/seed.ts exactly: 6 months of curated MRR per ticker plus
 * ~120 days of daily price snapshots (fair price from lib/pricing.ts with a
 * deterministic wiggle). Dates are baked in at generation time. Idempotent
 * via ON CONFLICT DO NOTHING; intended for a fresh project.
 */
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fairPrice } from "../lib/pricing";
import fixtures from "../fixtures/tickers.json";

const SNAPSHOT_DAYS = 120;

function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function monthStartUTC(offsetMonths: number): Date {
  const now = new Date();
  return new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + offsetMonths, 1)
  );
}

function iso(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function mrrAt(anchors: { time: number; mrr: number }[], time: number): number {
  if (time <= anchors[0].time) return anchors[0].mrr;
  for (let i = 0; i < anchors.length - 1; i++) {
    const a = anchors[i];
    const b = anchors[i + 1];
    if (time >= a.time && time <= b.time) {
      const f = (time - a.time) / (b.time - a.time || 1);
      return a.mrr + f * (b.mrr - a.mrr);
    }
  }
  return anchors[anchors.length - 1].mrr;
}

/** Deterministic starting sentiment in ±0.18 — mirrors scripts/seed.ts. */
function initialSentiment(symbol: string): number {
  const r = mulberry32(hashString(symbol + ":sentiment"))();
  return Math.round((r * 2 - 1) * 0.18 * 10000) / 10000;
}

const tickerRows: string[] = [];
const mrrRows: string[] = [];
const snapRows: string[] = [];

for (const fixture of fixtures.tickers) {
  const id = randomUUID();
  const listedAt = monthStartUTC(-(fixture.mrr.length - 1));
  tickerRows.push(
    `(${q(id)}, ${q(fixture.symbol)}, ${q(fixture.name)}, ${q(fixture.pitch)}, ${q(fixture.founder_handle)}, ${initialSentiment(fixture.symbol)}, true, ${q(listedAt.toISOString())})`
  );

  const months = fixture.mrr.map((mrr, i) => ({
    month: monthStartUTC(-(fixture.mrr.length - 1 - i)),
    mrr,
  }));
  for (const { month, mrr } of months) {
    mrrRows.push(`(${q(id)}, ${q(iso(month))}, ${mrr}, 'curated')`);
  }

  const anchors = months.map(({ month, mrr }) => ({
    time: month.getTime(),
    mrr,
  }));
  const rand = mulberry32(hashString(fixture.symbol));
  const phase = rand() * Math.PI * 2;
  for (let d = SNAPSHOT_DAYS; d >= 0; d--) {
    const day = new Date(Date.now() - d * 86400_000);
    const mrr = mrrAt(anchors, day.getTime());
    const fair = fairPrice(mrr);
    const wiggle =
      0.03 * Math.sin((SNAPSHOT_DAYS - d) / 5 + phase) + (rand() - 0.5) * 0.04;
    snapRows.push(
      `(${q(id)}, ${q(iso(day))}, ${(fair * (1 + wiggle)).toFixed(6)}, ${fair.toFixed(6)}, 0, ${mrr.toFixed(2)})`
    );
  }
}

const sql = `-- Generated by scripts/generate-seed-sql.ts on ${iso(new Date())}.
-- Fixture data for a fresh project: 20 tickers, 6 months of curated MRR,
-- ~${SNAPSHOT_DAYS} days of price snapshots. Run AFTER 0001_init.sql.
-- Idempotent on a fresh database; re-generate rather than hand-editing.

insert into public.tickers (id, symbol, name, pitch, founder_handle, sentiment, fixture, listed_at) values
${tickerRows.join(",\n")}
on conflict (symbol) do nothing;

insert into public.mrr_updates (ticker_id, month, mrr, source) values
${mrrRows.join(",\n")}
on conflict (ticker_id, month) do nothing;

insert into public.price_snapshots (ticker_id, day, price, fair_price, sentiment, mrr) values
${snapRows.join(",\n")}
on conflict (ticker_id, day) do nothing;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(
  `Wrote supabase/seed.sql — ${tickerRows.length} tickers, ${mrrRows.length} MRR rows, ${snapRows.length} snapshots.`
);
